name:                incremental-scheme-compiler
version:             0.1.0.0
github:              "githubuser/incremental-scheme-compiler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/incremental-scheme-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- parsec
- text
- mtl
- containers
- unordered-containers
- process
- syb
- hashable

library:
  source-dirs: src

executables:
  incremental-scheme-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - incremental-scheme-compiler

tests:
  incremental-scheme-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - incremental-scheme-compiler
